### PR TITLE
Travel-module

### PR DESCRIPTION
**Pull request by gugakatsi**

### CODE REVIEW

**Comment by Swati4star** [comment]
The following activities should also be moved to travel folder:
`My Trips` , `MyTripsInfo`
`SelectModeOfTransport`
`TrainList`, `BusList`, `CarDirections`
`Hotels`
`ShoppingCurrentCity`
`MapRealTimeActivity`

**Comment by gugakatsi** [comment]
I'll do it in few minutes.

**Comment by Vatican-Cameos** [comment]
Can I work on this ?

**Comment by Swati4star** [comment]
@Vatican-Cameos 
Yes, you can start working on this issue.

Resolve the conflicts & move the files as mentioned in my previous comment.

**Comment by Swati4star** [comment]
@gugakatsi You got to resolve the conflicts.

**Pull request closed without merging**
