### PR TITLE
base modules for presenter and view 

### PR DESCRIPTION
**Pull request by gugakatsi**

### CODE REVIEW

**Comment by Swati4star** [comment]
A fix for https://github.com/Swati4star/Travel-Mate/issues/44?

**Comment by gugakatsi** [comment]
Nope  , every presenter and view ( for example LoginView ) should extends those .

**Comment by gugakatsi** [comment]
i mean implement

**Comment by Swati4star** [comment]
Resolve the conflicts @gugakatsi

**Comment by Swati4star** [comment]
Feel free to new PR when you work on this issue.

**Pull request closed without merging**
