### PR TITLE
Users are redirected to login after signup instead of being loged in

### PR DESCRIPTION
**Pull request by momen-ghulmi**
a fix for bug #62 created by Swati4star

### CODE REVIEW

**Comment by Swati4star** [comment]
The actual login files are in the root Android folder. 
You need to make changes to the files in this folder :
https://github.com/project-travel-mate/Travel-Mate/tree/master/Android/app/src/main/java/io/github/project_travel_mate/login

**Comment by momen-ghulmi** [comment]
the files you mentioned are the ones I edited 
I pushed two changes after I tested it and made sure it's working

**Comment by Swati4star** [comment]
The build is failing too. 
Also, check the files changed. 
Why have you created this new heirarchy of files?
https://github.com/momen-ghulmi/Travel-Mate/tree/master/app/src/main/java/io/github/project_travel_mate/login

You are supposed to change these files : 
https://github.com/momen-ghulmi/Travel-Mate/tree/master/Android/app/src/main/java/io/github/project_travel_mate/login

Can you see the whole code is inside **Android** directory?

**Comment by momen-ghulmi** [comment]
it seems there is a problem with the GitHub integration 
I'm going to cancel this pull request and open a new one

**Pull request closed without merging**
