### PR TITLE
adding compass card to final position in list if there is no magnetic…

### LINKED ISSUE #514: If device does not have magnetic sensor, show compass at end in utilities
### Steps to reproduce
- select a device without magnetic sensor
- Go to utilities -> Compass

### Expected behaviour
In case the device does not have magnetic sensor,
 - show the compass card at the end in utilities section
- Grey out the card & on the top of card, show `Your device does not have magentic sensor` 
else
- The UI should be as is.

### Actual behaviour
After this issue (https://github.com/project-travel-mate/Travel-Mate/issues/457), an alert is shown if compass is opened & the device does not have magnetic senso

### PR DESCRIPTION
**Pull request by renanrhoden**
… sensor

## Description

Copied the logic to check if there are the necessary sensors from the compass activity and added to the utilities fragment and if so, add in the normal position. If there is any of them, add the compass card to the end of the list, as requested. 

Fixes #514 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
Hi @renanrhoden 

If the device does not have sensor, theUi should be like this (as mentioned in issue)

> show the compass card at the end in utilities section
Grey out the card & on the top of card, show `Your device does not have magentic sensor`

You have just moved the card to end, but not greyed it out & add text to it.

**Comment by Swati4star** [comment]
@renanrhoden Updates??

**Comment by renanrhoden** [comment]
Working on it

**Comment by Swati4star** [comment]
@renanrhoden ??

**Comment by renanrhoden** [comment]
@Swati4star done

**Pull request merged**
