### PR TITLE
migrate the project to androidX

### PR DESCRIPTION
**Pull request by Florence-Njeri**
## Migrate the project to androidX
I have migrated the project to androidX as well as updated butterknife dependency to 10.0.0 since thats the version that supports androidX

### CODE REVIEW

**Comment by Swati4star** [comment]
@Florence-Njeri Can you please suggest why is there a need to migrate the project to androidX?

**Comment by Florence-Njeri** [comment]
The libraries are better packages plus using support library is still okay but then you will not be able to get updates on those libraries because every new update on android will be rolled out to android x. Its up to you.

**Comment by prabhakar267** [comment]
If there is need to migrate to AndroidX, we will need to discuss it first. Since it doesn't seem necessary to migrate the project at this moment, closing the PR.

**Comment by Florence-Njeri** [comment]
You will eventually

**Pull request closed without merging**
