### PR TITLE
fixed no status bug

### LINKED ISSUE #250: Bug when user edits the status as nothing
### Steps to reproduce
- Go to profile page
- click on pencil icon by the side of status
- Remove everything that is already there in the status
- click on ✔️ 

### Expected behaviour
- User's status should be removed, and default message `Write something about yourself should be shown`

### Actual behaviour
- The status editbox is shown empty
- The status does not get updated to anything (go back & come to your profile again. The status is same as previous one)
- The following toast appears
screenshot_20180712-140533_02

### Endpoint to use
`remove-user-status`

### PR DESCRIPTION
**Pull request by aayushinigam**
# Description

Fixes #250 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
@aayushinigam There are merge conflicts

**Comment by Swati4star** [comment]
@aayushinigam It's failing

**Comment by aayushinigam** [comment]
I'll squash commits and update the PR

**Comment by Swati4star** [comment]
No need to squash. I'll squash & merge

**Comment by aayushinigam** [comment]
Oh okay!

**Pull request merged**
