### PR TITLE
Integrated Cities and Utilities Fragment with Home Fragment

### LINKED ISSUE #608: Integrate Cities Fragment & utilities fragment with Home Fragment
Describe your issue here.
Integrate Cities & utilities Fragment with Home Fragment

### Actual behaviour
Nothing happens onClick.

### Would you like to work on the issue?
Yes.

### PR DESCRIPTION
**Pull request by jddeep**
## Description
Integrated Cities Fragment with Home Fragment

Fixes #608 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
i updated issue tasks : https://github.com/project-travel-mate/Travel-Mate/issues/608

**Comment by jddeep** [comment]
@Swati4star Yeah I figured. Please review and merge.

**Comment by Swati4star** [comment]
is there any unlinked fragment left on home page?

**Comment by jddeep** [comment]
Nope, All covered.

**Comment by Swati4star** [comment]
Sure. I'll merge.
Let the build finish

**Comment by jddeep** [comment]
@Swati4star Build finished. 👍

**Pull request merged**
