### PR TITLE
Added Hotels Fragment

### LINKED ISSUE #585: Develop and link Hotels Fragment to HomeFragment.
Currently the Home page is UX/UI based and has no functionality. Child Activities/fragments are to be linked with it.

### Steps to reproduce
1. Go to Home from Nav Drawer.
2. The Home Page opens but does not respond on clicking the cards.

### Expected behaviour
On clicking a particular card, user should be taken to that particular fragment.

### Actual behaviour
Nothing.

### Would you like to work on the issue?
Yes.

### PR DESCRIPTION
**Pull request by jddeep**
## Description
Added Hotels Fragment to Home Fragment.

Fixes #585 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by jddeep** [comment]
@Swati4star Please review.

**Comment by Swati4star** [comment]
You said 
> the fragment needs to be developed from scratch and then needs to linked.
but i can see you are just opening the hotels activity.

**Comment by jddeep** [comment]
@Swati4star I figured that there is already a Hotels Fragment. Do you want me to make another one? I shall do it if you want to :)

**Comment by jddeep** [comment]
@Swati4star Please do tell me what to do. You can change the issue tag to`easy` OR if you want I can make another new fragment.

**Comment by Swati4star** [comment]
No need. This works.
Even I forgot that we already have this fragment.

**Pull request merged**
