### PR TITLE
Added user status in user profile screen #219

### PR DESCRIPTION
**Pull request by syedjahangirpeeran**
Kept the placeholders as per `https://github.com/project-travel-mate/server/pull/77/files` this PR.

### CODE REVIEW

**Comment by Swati4star** [comment]
Add a screenshot also.

**Comment by syedjahangirpeeran** [comment]
screenshot_20180709-103020

**Comment by Swati4star** [comment]
Some enhacements:
- Move the status line to the top. 
- Add three dots after yourself...
- Can we have a different pencil icon? (something without the square filled & just the pencil icon)
- API is also ready : https://github.com/project-travel-mate/server/issues/71

**Comment by Swati4star** [comment]
Add status info here also : https://github.com/project-travel-mate/Travel-Mate/blob/966c2a257f5244fd4f366056c9104a95baa2d850/Android/app/src/main/java/io/github/project_travel_mate/MainActivity.java#L291

**Pull request closed without merging**
