### PR TITLE
feat: Add Java 8 support & Convert to lambda expressions

### LINKED ISSUE #122: Provide support for Java 8 language features
### Steps to reproduce
N/A.

### Expected behaviour
Provide the support so that major features like `Lambda expressions`, `Default and static interface methods`, etc. can be put to use in the development.

### Actual behaviour
Not yet provided.

### Would you like to work on the issue?
Yes.

### PR DESCRIPTION
**Pull request by brijeshshah13**
Fixes #122.

@Swati4star Please review.

### CODE REVIEW

**Comment by Swati4star** [comment]
there are checkstyle errors. Fix those & look into the code if we can integrate lambda function elsewhere also.

**Comment by brijeshshah13** [comment]
@Swati4star I'm reformatting the whole codebase along with the checkstyle errors. Is it worth to increase the credibility of the issue?

**Comment by Swati4star** [comment]
The changes you have made looks good.

**Comment by brijeshshah13** [comment]
@Swati4star The Travis CI build has successfully passed ✌️

**Pull request merged**
