### PR TITLE
Improved the UI when there are no friends in a trip #186

### PR DESCRIPTION
**Pull request by syedjahangirpeeran**

### CODE REVIEW

**Comment by Swati4star** [comment]
@syedjahangirpeeran add the screenshot of when there are no friends in a trip

**Comment by syedjahangirpeeran** [comment]
screenshot_20180706-124925

**Comment by Swati4star** [comment]
The font size is too big. Make it normal only. Same as trip description.
Also, add a full stop at the end & make it underlined.

**Comment by syedjahangirpeeran** [comment]
screenshot_20180706-130731

**Pull request merged**
