### PR TITLE
resolve #737 - world clock UI update

### LINKED ISSUE #737: Improve world clock home page UI
wc

Some suggestions:
- Move "select timezone" and the "asia/kolkata" dropdown to same line
- Reduce the size of "Select timezone"

More suggestions are welcome

### PR DESCRIPTION
**Pull request by RyanMarzec**
## Description
resolves issue 737, changing "select timezone" size and moving "select timezone" and timezone list to same line. 

Before:
Capture

After:
after

Fixes #(issue)

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
- Leave some space to the left of `Select Timezone`
- Make the whole background white. I can see that at the bottom, background color becomes greyish.

**Comment by Swati4star** [comment]
why is your before UI different than the one in https://github.com/project-travel-mate/Travel-Mate/issues/737?

**Comment by RyanMarzec** [comment]
update1

as for the before, this is how it looked when I cloned the app, can you check your version to see if it is same as my before, or the one in #737 or if this is just an issue on my end?

**Comment by Swati4star** [comment]
Thank you for this PR, but https://github.com/project-travel-mate/Travel-Mate/pull/784 also fixes the same issue and that has been merged!

Can you pick up some other issue to work on?

**Pull request closed without merging**
