### PR TITLE
#494 - Clock Widget

### PR DESCRIPTION
**Pull request by jtj9817**
## Description
This WIP milestone now includes the widget configuration screen, fulfilling the 2nd feature request opened in this issue #494. 

### Android/app/src/main/AndroidManifest.xml
Added the necessary configuration for the widget to work properly
### Android/app/src/main/java/widget/ClockWidget.java
Activity file for the widget which it uses when it's created
### Android/app/src/main/java/widget/ClockWidgetConfigureActivity.java
Configuration activity when the widget is first created
### Android/app/src/main/res/drawable/clockwidget_preview.png
A preview image used for the Clock Widget to show the user what the widget will look like
### Android/app/src/main/res/layout/clock_widget.xml
Layout file for the clock widget
### Android/app/src/main/res/layout/clock_widget_configure.xml
Layout file for the configuration activity for the clock widget
### Android/app/src/main/res/values/strings.xml
Updated the strings to be used for the clock widget config activity
### Android/app/src/main/res/xml/clock_widget_info.xml
Defines the settings for the clock widget when it's instantiated 
### Other files
All the changes to other files are very minor changes. The changes on XML files that includes 'dimens.xml' in its name are related to the widget's layout size on the launcher/home screen. Changes to colors.xml is just a newline.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
@jtj9817 Is it a WIP or a complete working one?

**Comment by jtj9817** [comment]
It's a complete working one although only with Digital Clock interface. You can test it for yourself and see if it's satisfactory enough to be implemented in the official release of Travel Mate.

**Comment by Swati4star** [comment]
@jtj9817 We already have a world clock option in the naivigation drawer -> utilities.
Do we need a new screen that you have created? or can we just use the settings from the above screen only?

**Comment by jtj9817** [comment]
@Swati4star The configuration screen for the widget is a separate process instantiated by creating a widget, therefore the configuration screen that I created will be needed. I'm aware of the World Clock option in the Utilities section of the app but replicating that in the configuration screen is difficult and my implementation is sufficient enough.

**Comment by jtj9817** [comment]
@Swati4star any updates for this PR? Any steps I should take to open a new PR?

**Comment by Swati4star** [comment]
Merged! Thanks @jtj9817

**Pull request merged**
