### PR TITLE
Added missing drawables for weather forecast

### LINKED ISSUE #730: Bug:Delhi weather forecast causes app crash

### PR DESCRIPTION
**Pull request by aman0408**
## Description
App crashing on opening weather forecast
Fixes #730 
Fixed crash happening on opening weather forecast by adding drawables

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [ ] `./gradlew assembleDebug assembleRelease`
- [ ] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
@aman0408 Great!
- Can you also add the  check (if drawable exists) where the app was crashing 
- Also, these images (which you just added) show up as unused drawables in Android studio. Is there a way to disable the warning for these in future so that these doesnt get removes again? (This particular issue can be solved in another PR/issue also)

**Comment by aman0408** [comment]
> @aman0408 Great!
> 
> * Can you also add the  check (if drawable exists) where the app was crashing
> * Also, these images (which you just added) show up as unused drawables in Android studio. Is there a way to disable the warning for these in future so that these doesnt get removes again? (This particular issue can be solved in another PR/issue also)

Okay i will add the if condition and create another request. About the second part I'll figure something out.

**Comment by Swati4star** [comment]
You dont have to create another request. You can add the changes in this PR only.

**Comment by aman0408** [comment]
I didn't know I could update files in the same request. Anyway, I have added the if condition and pushed again on my branch. Is there anything else I need to do to update the PR?

**Comment by aman0408** [comment]
About the unused resources part, we could create a dummy file which references these resources so they're not marked as unused

**Pull request merged**
