### PR TITLE
More than 10 cities enabled.

### LINKED ISSUE #262: City Dialog shows only limited cities
### Steps to reproduce
First way
- Go to `Travel`. Select `Hotels`. The following dialog opens up

Second way
- Go to `My Trips`. Select `+` icon. Select `Select City`. The dialog opens up.

This dialog currently has only 10 cities. The autocomplete also uses these 10 cities only.

### Expected behaviour
- We have a number of cities on the server.
- Use the city automcomplete API to dynamically fetch those based on what user has typed.

### PR DESCRIPTION
**Pull request by jddeep**
## Description
More than 10 cities enabled.

Fixes #262 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by jddeep** [comment]
@Swati4star Please review and do tell whether there is a better Api get request available.

**Comment by Swati4star** [comment]
This change wont enable more cities in the dialog.

**Comment by jddeep** [comment]
Well but the response from the Api is the legitimate. It gives results according to the query be it 10 or 5000

**Comment by jddeep** [comment]
@Swati4star can you say what more can be done?

**Comment by Swati4star** [comment]
Wait. Ill check it once locally also.

**Comment by jddeep** [comment]
Okay do tell me what do you observe and any suggestions.

**Comment by jddeep** [comment]
@Swati4star Okay do tell me what do you observe and any suggestions.

**Comment by Swati4star** [comment]
Done! and Kudos on your first contribution to this project 👍

**Pull request merged**
