### PR TITLE
Color change

### LINKED ISSUE #256: Prevent 2 colors from being same
screenshot_20180712-060153

In the above screenshot both cities are having the same color. Prevent this from happening?

### PR DESCRIPTION
**Pull request by Mudra01**
Fixes #256 
the issue for same color would not be a problem as i have made a more random selection of color.
## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [ ] `./gradlew assembleDebug assembleRelease`
- [ ] `./gradlew checkstyle`

# Checklist:
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by syedjahangirpeeran** [comment]
It's possible to get two colors same again. Increasing randomness doesn't solve the issue, only uniquely assigning them does.

**Comment by Swati4star** [comment]
And also, checks are failing 

You should create an array of 10 color values. Shuffle it. And then, uniquely assign it to corresponding card.

**Comment by Mudra01** [comment]
I am still not able to figure out how to get it to uniquely assign as the method is called every time and without any parameters being passed i cannot figure out a way.

**Comment by Swati4star** [comment]
You can pass the colors array as a parameter then

**Pull request closed without merging**
